### ISSUE TITLE
onClick not working in carousel3

### ISSUE THREAD

**Issue by KevinHdezVaz** [ImaginativeShohag/Why-Not-Image-Carousel#101]
in carousel 3 , the onclick method does not work when placed in the carouselListener.

        binding.carousel3.carouselListener = object : CarouselListener {

            override fun onCreateViewHolder(
                layoutInflater: LayoutInflater,
                parent: ViewGroup
            ): ViewBinding {
                return ItemCustomFixedSizeLayout1Binding.inflate(layoutInflater, parent, false)
            }

            override fun onBindViewHolder(
                binding: ViewBinding,
                item: CarouselItem,
                position: Int
            ) {
                val currentBinding = binding as ItemCustomFixedSizeLayout1Binding
                currentBinding.imageView.apply {
                    scaleType = ImageView.ScaleType.CENTER_CROP
                    setImage(item, R.drawable.carousel_default_placeholder)
                }
            }

            override fun onClick(position: Int, carouselItem: CarouselItem) {
                Toast.makeText(
                    this@MenuActivity,
                    "You clicked at position ${position + 1}.",
                    Toast.LENGTH_SHORT
                )
                    .show()
            }

        }

**Comment by MrNtlu** [comment]
I think it is an expected behaviour. You have to pass your own clicking method in onBindViewHolder.

```Kotlin
currentBinding.root.setOnClickListener {
  // Your click
}
```

https://github.com/ImaginativeShohag/Why-Not-Image-Carousel/blob/3a126770c2d713fc5d3ec444cb313b096427ee11/whynotimagecarousel/src/main/java/org/imaginativeworld/whynotimagecarousel/listener/CarouselListener.kt#L32

**Comment by ImaginativeShohag** [comment]
Yes, it is expected.
