### ISSUE TITLE
Update carousel

### ISSUE THREAD

**Issue by AmirMehr** [ImaginativeShohag/Why-Not-Image-Carousel#109]
How can I update carousel items?
How can I have something like "NotifyDataSetChanged"?

**Comment by ImaginativeShohag** [comment]
Use `carousel.setData(list)`.

**Comment by AmirMehr** [comment]
Thanks, I found it, but it is not as meaningful as "NotifyDataSetChanged".
It is similar to setting data for the first time, not updates, but it works
