### ISSUE TITLE
Loop slider no supported

### ISSUE THREAD

**Issue by ToghrolRc** [ImaginativeShohag/Why-Not-Image-Carousel#11]
Hi there , first i'm sorry for my bad English!
i'm using this library and it is good , but LOOP slide is not supported. can you make this possible please?
i want like this:
img1 > img2 > img3 > img4 > **img1** > **img2** ...

**Comment by ImaginativeShohag** [comment]
If you are looking for auto-sliding carousel, use the `start()` and `stop()` functions. It will auto slide from img1 to img4 and then restart from img1.

But if you want infinite scrolling, like after img4, img1 will show its right side, then you can't do it in this library so far. Maybe in the future, it will be added to the library.

**Comment by ToghrolRc** [comment]
yes i want infinite scrolling , can you do that?

**Comment by ImaginativeShohag** [comment]
No current library cannot do that.

**Comment by LocalXpert** [comment]
Hey
can you tell us how to do infinite scrolling we want to add these features in this library.

**Comment by jcaverhagen** [comment]
I would also like inifinity scrolling

**Comment by ImaginativeShohag** [comment]
Coming soon in version 2. :)

**Comment by ImaginativeShohag** [comment]
The feature is added in version 2. Enjoy.
