### ISSUE TITLE
How to scroll to the desired position.

### ISSUE THREAD

**Issue by hiepbeos** [ImaginativeShohag/Why-Not-Image-Carousel#119]
I wanna scroll to a item i want, not next or previous item.

**Comment by ImaginativeShohag** [comment]
Use `currentPosition` like this:

```kotlin
binding.carousel1.currentPosition = 3 // 3 is the target position.
```

**Comment by hiepbeos** [comment]
It worked thank you.

**Comment by hiepbeos** [comment]
I used binding.carousel1.currentPosition = 3 but in callback onScrolled, I get position = 0.
I dont know why?

**Comment by hiepbeos** [comment]
I want to update the central view every time I drag to an item. Do you have any suggestions for doing that? 
I am having to call setData in onScrolled.

**Comment by hiepbeos** [comment]
![Screenshot_20240624_130110](https://github.com/ImaginativeShohag/Why-Not-Image-Carousel/assets/20041362/403d1e2c-5b84-40f5-8c53-7846348733b8)
like that

**Comment by ImaginativeShohag** [comment]
Please check [this](https://github.com/ImaginativeShohag/Why-Not-Image-Carousel/blob/master/sample/src/main/java/org/imaginativeworld/whynotimagecarousel/sample/KotlinActivity.kt#L257-L268) example and use `onScrollStateChanged`. In the given example, I am changing the caption based on the currently selected item/centered item.
