### ISSUE TITLE
Unable to start activity ComponentInfo{com.wpapp/com.wpapp.ImageActivity}: android.view.InflateException: Binary XML file line #9: Binary XML file line #9: Error inflating class org.imaginativeworld.whynotimagecarousel.ImageCarousel

### ISSUE THREAD

**Issue by chandra-meet** [ImaginativeShohag/Why-Not-Image-Carousel#15]
I have android:theme="@style/Theme.AppCompat.Light.NoActionBar" then this code is not working please make it work without action bar

**Comment by ImaginativeShohag** [comment]
Please use the material components to use this library.

Add the following dependency to your project:

```
dependencies {
    // ...

    // Material Components for Android
    implementation 'com.google.android.material:material:1.1.0'

    // ...
}
```

And must use `@style/Theme.MaterialComponents.Light.NoActionBar` insted of AppCompat theme.
