### ISSUE TITLE
Auto play not wokring

### ISSUE THREAD

**Issue by MohammadDesouky** [ImaginativeShohag/Why-Not-Image-Carousel#16]
Auto play with various numbers of delay  didn't work, I was trying on android 10 real device

```
 carousel.autoPlayDelay = 150
 carousel.autoPlay = true
```

**Comment by ImaginativeShohag** [comment]
If you provide me a sample project then I can check the problem.

You can run the sample project from [here](https://github.com/ImaginativeShohag/Why-Not-Image-Carousel/tree/master/sample).
