### ISSUE TITLE
Pause auto sliding when touching image

### ISSUE THREAD

**Issue by FakhourMed** [ImaginativeShohag/Why-Not-Image-Carousel#19]
Hi guys,

thanks Mahmudul Hasan for your simple and awesome image slider,

I want to pause the auto sliding until i release my finger from the slider, there is a way to do this with this lib??

thanks

**Comment by ImaginativeShohag** [comment]
No, so far no official way to do this.

**Comment by ImaginativeShohag** [comment]
The feature is added in version 2. Enjoy.
