### ISSUE TITLE
How to show previous and next img 

### ISSUE THREAD

**Issue by iamabs2001** [ImaginativeShohag/Why-Not-Image-Carousel#23]
- show previous and next image ? (example last carousel )
- fix image size in center and left and right image

**Comment by ImaginativeShohag** [comment]
> show previous and next image ? (example last carousel )

Full source code of the sample can be found here: https://github.com/ImaginativeShohag/Why-Not-Image-Carousel/tree/master/sample

> fix image size in center and left and right image

You can use the `app:scalingFactor="0.15"` attribute to set the scaling percentage of the left & right image. `0.15` means the left & right side image will be 15% smaller.

**Comment by iamabs2001** [comment]
still not getting output. Can you give full xml and java code. which look like google play store image slider.

**Comment by iamabs2001** [comment]
```xml

<org.imaginativeworld.whynotimagecarousel.ImageCarousel
        android:id="@+id/home_carousel"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        app:scalingFactor="0.15"/>

```

**Comment by ImaginativeShohag** [comment]
For showcase type, you have to create custom layout for the carousel items. The parent of the custom layout must have fixed width. [Here](https://github.com/ImaginativeShohag/Why-Not-Image-Carousel/blob/81722956c5c6f281be9b680d54e2af75cdb1f138/sample/src/main/res/layout/custom_fixed_size_item_layout.xml#L1-L23) is an example. And add it like [this](https://github.com/ImaginativeShohag/Why-Not-Image-Carousel/blob/81722956c5c6f281be9b680d54e2af75cdb1f138/sample/src/main/res/layout/activity_kotlin.xml#L58).
