### ISSUE TITLE
Could not find implmention(build.gradle)

### ISSUE THREAD

**Issue by itapiatu** [ImaginativeShohag/Why-Not-Image-Carousel#25]
Hi ,I've just seen this amazing library,but I've encountered problems when importing it.
`Could not find org.imaginativeworld.whynotimagecarousel:whynotimagecarousel:1.2.1.
Required by:
    project :app`

Anything I'm doing wrong?

**Comment by ImaginativeShohag** [comment]
Please again just `Sync Project with Gradle Files`, it is solved.

We updated the GitHub repository readme before updating the library to maven. Sorry for that.
