### ISSUE TITLE
Thumbnails

### ISSUE THREAD

**Issue by alexschled** [ImaginativeShohag/Why-Not-Image-Carousel#28]
Hello,

is it possible to view thumbnails of the images? 

Thank you

**Comment by ImaginativeShohag** [comment]
What kind of thumbnails? Can you please give me an example preview?

**Comment by alexschled** [comment]
So it could look like this one here:

[https://miro.medium.com/max/294/1*BW_PgOBnsAWuXLg9ZkZjRg.jpeg](url)

**Comment by ImaginativeShohag** [comment]
No. It is not possible. But you can manually implement it using another recycler view for bottom thumbnails.
