### ISSUE TITLE
why autoplay not working?

### ISSUE THREAD

**Issue by abimanyu07** [ImaginativeShohag/Why-Not-Image-Carousel#30]
why autoplay not working?

**Comment by abimanyu07** [comment]
when i add autoplay on activity not working but i add on xml working

**Comment by ImaginativeShohag** [comment]
I tested and the `start()` and `stop()` functions are working as expected. Can you please give me your XML and carousel init codes? So that I can further test your specified case.

**Comment by risalfajar** [comment]
It's working fine for me, you should show us your code.
