### ISSUE TITLE
Change indicator color/tint

### ISSUE THREAD

**Issue by risalfajar** [ImaginativeShohag/Why-Not-Image-Carousel#34]
Please add an attribute to change indicator color. I have tried `foregroundTint` an `backgroundTint` but it's not changing the color.

**Comment by ImaginativeShohag** [comment]
Add your custom `CircleIndicator` and customize it. Then set the custom indicator with the carousel using `setIndicator()` method. Please see the sample's 4th example carouse for details.

Supported `CircleIndicator` library: https://github.com/ongakuer/CircleIndicator
