### ISSUE TITLE
addData() function should be named submitData() or setData()

### ISSUE THREAD

**Issue by risalfajar** [ImaginativeShohag/Why-Not-Image-Carousel#35]
I've looked at the implementation

**ImageCarousel.kt**
```
fun addData(data: List<CarouselItem>) {
        adapter?.apply {
            addAll(data)
            this@ImageCarousel.data = data
            this@ImageCarousel.dataSize = data.size
            initOnScrollStateChange()
        }
    }
```

**CarouselAdapter.kt**
```
fun addAll(dataList: List<CarouselItem>) {
        this.dataList.clear()

        this.dataList.addAll(dataList)
        notifyDataSetChanged()
    }
```

As you can see that calling addData will not just adding data, but clear all previous data too. It should be called setData, submitData, or maybe replaceData.

Or you can have both, addData and setData.

**Comment by ImaginativeShohag** [comment]
Good observation. You are right. Noted for next release.
