### ISSUE TITLE
Getting black spaces in corners

### ISSUE THREAD

**Issue by rama-2402** [ImaginativeShohag/Why-Not-Image-Carousel#36]
Hi, First of all the library is awesome. I love how easy it is to implement it. As you can see my problem from the attachment. There are weird black spaces that fills up and becomes a sharp edged rectangle. But I wanted rounded corners. Can you please provide me a solution on how to fix this? 

Edit: If i use image with rounded corners, it fills the gap with black color as seen in the attachment
if i use image with sharp corners like normal images then the carouel view has straight pointy corners and not the rounded corner style.

I have used the same "Theme.MaterialComponents.Light.NoActionBar" as my app theme. 

Please let me know if i need to share any file for reference to fix the issue.

![image_corners](https://user-images.githubusercontent.com/68183781/114313823-c82ddf00-9b15-11eb-8d43-65cd8f1b67d2.jpg)

**Comment by rama-2402** [comment]
FYI, if anyone else is facing this issue. I have found a workaround. 

1. Create a drawable resource file with any corner radius you want.
2. Set the drawable file as the background for the carousel view

`android:background="@drawable/btn_bg_layout"`

3. write this line of code in your activity or fragment file

`carousel_view_id.clipToOutline = true`

Now issue will be fixed. You can add elevation as well to have more pleasing look :)

Hope this helps :)

**Comment by ImaginativeShohag** [comment]
Do you tried setting the carousel background with your desired color using `app:carouselBackground="@color/xyz_color"`?

You already fixed the issue, but just making sure is it really a bug or not. :)

**Comment by rama-2402** [comment]
@ImaginativeShohag  Yes i have tried the background with colors and drawable layout files but nothing seemed to work except if i tried the background layout file with clipToOutine = true. Anyway thanks for checking back. Appreciate it :)
