### ISSUE TITLE
Wrong position index

### ISSUE THREAD

**Issue by behnawwm** [ImaginativeShohag/Why-Not-Image-Carousel#43]
I receive Wrong `position` indexes on `onScrollStateChanged` !
The values are about the MAX_SIZE of integer (1073741823) !!
I should use `position-1073741823` to make it work! (position 0 is OK)

What's the issue?

**Comment by ImaginativeShohag** [comment]
It is a bug. I am publishing a fix as soon as I can.

Mean time you can just do this `val realPosition = position % dataList.size`.

**Comment by ImaginativeShohag** [comment]
Please use version 2.0.3. The bug is fiexed. :)

**Comment by behnawwm** [comment]
I still have the problem!

**Comment by ImaginativeShohag** [comment]
I forget to fix all places :disappointed:. Will check all possible places this time.

Meantime, you can just mod the value with the data size like this `val realPosition = position % dataList.size`.
