### ISSUE TITLE
Does not work autoPlay after the slide.

### ISSUE THREAD

**Issue by roman-a-marchenko** [ImaginativeShohag/Why-Not-Image-Carousel#45]
1. Setup autoPlay = true
2. Have more than 1 image.

We are waiting for 1 slide auto-scrolling, we move our finger to the next slide, and auto-scrolling does not work anymore. It starts working if you click on the slide.

**Comment by ImaginativeShohag** [comment]
It is a known bug. Let me see if I can found any solution.
