### ISSUE TITLE
[Question] When Position is 0 and left swipe, can i move it to the rear?

### ISSUE THREAD

**Issue by leejooheon** [ImaginativeShohag/Why-Not-Image-Carousel#51]
**[Environment]**
Android Target SDK: 30
Why-Not-Image_Carousel version: 2.0.2
Three Carousel items.

When Position is 0 (received from CarouselOnScrollListener), there is a conditions that blocks left swipe performed.
I want to move it to the rear when Position is 0.
Is there any way to fix it?

**Comment by ImaginativeShohag** [comment]
Can't understand the problem. Can you give a screenshot or gif, please?

**Comment by leejooheon** [comment]
> Can't understand the problem. Can you give a screenshot or gif, please?

![capture](https://user-images.githubusercontent.com/17900820/132430720-44179958-de6b-434f-bbf6-0618f42d1fad.gif)

Hi Shohag, Sorry my english skill is not good.

like above gif, Swipe is blocked when the Position received from the CarouselOnScrollListener is 0.
I want to move it to the back at this point.

**Comment by ImaginativeShohag** [comment]
The default behavior is the carousel will work infinitely, which means it should slide left.

Can you please give me a sample XML with activity code, so that I can check you it is not working?

**Comment by leejooheon** [comment]
> The default behavior is the carousel will work infinitely, which means it should slide left.
> 
> Can you please give me a sample XML with activity code, so that I can check you it is not working?

oh my..  yes! it works perfectly when i can't use carousel.setImageScaleType.
Do you know anything about it?

My time zone is now 1 am.. I think I'll have to give you the code the next day after sleeping.

**Comment by leejooheon** [comment]
I'm really sorry for being so late.
As a result of checking, setImageScaleType after addData, it doesn't work infinitely.

```java
    private void setCarouselView() {
        ImageCarousel carousel = findViewById(R.id.carousel);

        List<CarouselItem> items = new ArrayList<>();
        for (int i = 0; i < 3; i++) {
            CarouselItem carouselItem = new CarouselItem(R.drawable.no_image_rc);
            items.add(carouselItem);
        }

        carousel.setImageScaleType(ImageView.ScaleType.CENTER_CROP); // working
        carousel.addData(items);
//        carousel.setImageScaleType(ImageView.ScaleType.CENTER_CROP); // not working
    }
```
Thanks!

**Comment by ImaginativeShohag** [comment]
Ok. The last step should be adding the data. As it is working, I am closing this issue. :)
