### ISSUE TITLE
Custom CarouselItem

### ISSUE THREAD

**Issue by AKK-Tech** [ImaginativeShohag/Why-Not-Image-Carousel#52]
List<CarouselItem> list = new ArrayList<>();

// Image URL with caption
list.add(
    new CarouselItem(
        "https://images.unsplash.com/photo-1532581291347-9c39cf10a73c?w=1080",
        "Photo by Aaron Wu on Unsplash"
    )
);

I want to use a custom CarouselItem model to add new fields for the carousel.setData(list).

eg.
new CarouselItem(
        "imageUrl",
        "caption",
        "type",
        "action",
       ...
    )

**Comment by ImaginativeShohag** [comment]
Currently, you can't use a custom `CarouselItem` directly. You can still use your item list. Just use `CarouselItem` for the image URL or just `new CarouseItem("")`, then use your item list in the `onBindViewHolder`.

Example:

```
List<CustomDataModel> dataList = new ArrayList<>();
dataList.add( // custom data );

 List<CarouselItem> list = new ArrayList<>();
list.add(new CarouselItem("http://image-url-here");

        binding.carousel.setCarouselListener(new CarouselListener() {
        
            @Override
            public void onBindViewHolder(@NotNull ViewBinding binding, @NotNull CarouselItem item, int position) {
                CustomDataModel item = dataList.get(position);
                // use user custom item
            }
        });
```
