### ISSUE TITLE
After reseting new list with setData indicator not showing

### ISSUE THREAD

**Issue by Narek1994** [ImaginativeShohag/Why-Not-Image-Carousel#61]
Hi
Thanks for the library
When we set data at first time, it correctly shows indicator at first position, but if we reset new data with the same setData method, indicator gets hidden, and shows after manual scrolling

First time
<img width="247" alt="Screen Shot 2021-10-17 at 12 50 42 AM" src="https://user-images.githubusercontent.com/29127973/137601794-35fa63fe-0a3b-4731-8e9d-9e127956a141.png">

Second time
<img width="229" alt="Screen Shot 2021-10-17 at 12 50 51 AM" src="https://user-images.githubusercontent.com/29127973/137601804-4d195734-1419-4341-b794-6d35b9de7876.png">

**Comment by ImaginativeShohag** [comment]
Noted. Will check the problem.

**Comment by jordanjanaq** [comment]
Same here. Any news?

**Comment by jordanjanaq** [comment]
I don't know if this is right, but I was trying to fix it, and it only works with currentPosition = 0 after createIndicator.

<img width="513" alt="Captura de Pantalla 2022-01-06 a la(s) 12 39 19" src="https://user-images.githubusercontent.com/48919342/148426321-3ccd2e36-28f9-44e3-bf7a-b2c57bd8d1ff.png">

**Comment by ImaginativeShohag** [comment]
Not found a solution yet. Adding `currentPosition = 0` also not work in my test.

**Comment by ImaginativeShohag** [comment]
@Narek1994 , @jordanjanaq Please check version 2.0.6. This fix should solve the problem.
