### ISSUE TITLE
app:carouselType="SHOWCASE" *Not working*

### ISSUE THREAD

**Issue by shahzad1** [ImaginativeShohag/Why-Not-Image-Carousel#70]
Tried app:carouselType="SHOWCASE" attribute in xml, but its showing the carousel in Block style.

**Comment by ImaginativeShohag** [comment]
Try also adding `carousel.carouselType = CarouselType.SHOWCASE` in your source code. It should work.

**Comment by shahzad1** [comment]
> Try also adding `carousel.carouselType = CarouselType.SHOWCASE` in your source code. It should work.

Already doing this, but its not working
`
 carousel.setCarouselType(CarouselType.SHOWCASE);
 carousel.setCarouselGravity(CarouselGravity.CENTER);
`

**Comment by ImaginativeShohag** [comment]
Can you share your XML layout code and carousel code?

**Comment by shahzad1** [comment]
Here you go
**xml**
`            <org.imaginativeworld.whynotimagecarousel.ImageCarousel
                app:imageScaleType="fitXY"
                app:showBottomShadow="false"
                app:showTopShadow="false"
                app:showCaption="false"
                app:showIndicator="true"
                app:carouselBackground="#ffffff"
                app:showNavigationButtons="false"
                app:carouselType="SHOWCASE"
                app:carouselGravity="CENTER"
                app:scaleOnScroll="true"
                app:scalingFactor="0.15"
                app:carouselPadding="10dp"
                app:autoWidthFixing="true"
                app:autoPlay="true"
                android:layout_margin="10dp"
                app:autoPlayDelay="3000"
                app:infiniteCarousel="true"
                app:touchToPause="true"
                android:id="@+id/carousel"
                android:layout_width="match_parent"
                android:layout_height="180dp" />
`
**Java**
`carousel.registerLifecycle(getViewLifecycleOwner());
        carousel.setCarouselType(CarouselType.SHOWCASE);
        carousel.setCarouselGravity(CarouselGravity.CENTER);`

**Comment by ImaginativeShohag** [comment]
You have to give a **custom layout** with a **fixed width** for your carousel, to get the show-case effect.

Check out the sample from [here](https://github.com/ImaginativeShohag/Why-Not-Image-Carousel/tree/master/sample).

Especially [this](https://github.com/ImaginativeShohag/Why-Not-Image-Carousel/blob/7566ed2cc78549089079fc3c32e3b2f0f2613b77/sample/src/main/java/org/imaginativeworld/whynotimagecarousel/sample/KotlinActivity.kt#L189) code and [this](https://github.com/ImaginativeShohag/Why-Not-Image-Carousel/blob/7566ed2cc78549089079fc3c32e3b2f0f2613b77/sample/src/main/res/layout/item_custom_fixed_size_layout_1.xml) layout.
