### ISSUE TITLE
How can I make indicators go at the bottom of the image

### ISSUE THREAD

**Issue by shahwaiz90** [ImaginativeShohag/Why-Not-Image-Carousel#71]
![Screenshot 2022-01-02 at 7 14 48 PM](https://user-images.githubusercontent.com/410180/147878561-6f2347a7-244d-4033-8834-5599cb2b786a.png)

Not sure if library is supporting something like this. But in readme instructions there was a sample related to this.

**Comment by jrojas03** [comment]
How at the image ends? Can you explain?

**Comment by shahwaiz90** [comment]
![Screenshot 2022-01-03 at 10 51 04 AM](https://user-images.githubusercontent.com/410180/147902685-da6fb15c-e016-411a-a6be-b203d24da926.png)
Some thing like this. But without the caption. The indicators should be below the image.

**Comment by jrojas03** [comment]
You have to use app:showIndicator="false" and then:

https://github.com/ongakuer/CircleIndicator

Use this and put CircleIndicator2 where you want in xml.
![Captura de Pantalla 2022-01-03 a la(s) 01 44 57](https://user-images.githubusercontent.com/26355419/147905132-46734786-9955-45ee-a82c-7779c940f1f0.png)
 
 and then pass the indicator id in code:
setIndicator(indicator)

**Comment by shahwaiz90** [comment]
Thanks for your reply. I tried this, but indicators are not visible.
<img width="604" alt="Screenshot 2022-01-03 at 12 33 22 PM" src="https://user-images.githubusercontent.com/410180/147907751-53d2ef31-2707-46db-ab90-3ef59f1d177a.png">


<img width="387" alt="Screenshot 2022-01-03 at 12 44 18 PM" src="https://user-images.githubusercontent.com/410180/147908485-839d257e-0f19-4fcc-b2e6-51220b4e7ca3.png">

 
<img width="792" alt="Screenshot 2022-01-03 at 12 46 42 PM" src="https://user-images.githubusercontent.com/410180/147908638-0a353649-d454-400f-9335-15ebefa4bf8a.png">

**Comment by ImaginativeShohag** [comment]
Just move last 2 line code (`val customeIndicator` and `setIndicator`) before `setData` function. This should solve your problem.
