### ISSUE TITLE
Setting "infiniteCarousel" programmatically should reinitialize the adapter

### ISSUE THREAD

**Issue by varchar20** [ImaginativeShohag/Why-Not-Image-Carousel#74]
Hello,

I noticed there is a problem while loading photos that are dynamically changing and when the photo list may contain only one item. So, for example, when the photos are pulled from some API.

Consider such a case:
When the photo list contains only one item, you programmatically change the "infiniteCarousel" flag to "false", because there is no point in looping one photo infinitely, so the carousel should behave like one static photo.

Otherwise, when the photo list contains more than one item, you set the "infiniteCarousel" flag to "true", because that is the default and desired behavior.

The problem is that changing this flag programmatically does not reinitialize the adapter, thus this change is not noticed by the carousel at all (in terms of displaying photos). 
After changing "infiniteCarousel" flag, you need to change another variable (imageScaleType, imagePlaceholder or autoWidthFixing) if you want this change to take place. I mean invoking initAdapter() method.

I think that changing the "infiniteCarousel" flag programmatically should reinitialize the adapter, so the carousel can behave as I described.

Thank you in advance for your feedback and have a great day!

Best regards,
varchar20

**Comment by ImaginativeShohag** [comment]
Good observations. Noted.

**Comment by ImaginativeShohag** [comment]
The problem is resolved. Here is the note from the release note:

Before changing the `infiniteCarousel`, it is better to clear the data-set, then change the `infiniteCarousel` attribute and finally set the data. Changing the `infiniteCarousel` with existing data can create undesirable issues.

Example code:

```kotlin
// Step 1: Clear existing data
carousel.setData(emptyList())

// Step 2: Change infiniteCarousel
carousel.infiniteCarousel = true // or false

// Step 3: Finally, set data
carousel.setData(itemList) // itemList is List<CarouselItem>
```
