### ISSUE TITLE
Custom Transition for carousel

### ISSUE THREAD

**Issue by rohan-317** [ImaginativeShohag/Why-Not-Image-Carousel#78]
### is there any way to make transition slower/faster in carousel?

**Comment by ImaginativeShohag** [comment]
No. The default implementation of the carousel uses `RecyclerView`'s `smoothScrollToPosition` method to animate scroll. You can fork the repo and try [this](https://stackoverflow.com/questions/32241948/how-can-i-control-the-scrolling-speed-of-recyclerview-smoothscrolltopositionpos).
