### ISSUE TITLE
how use wrap_content for height ?

### ISSUE THREAD

**Issue by hosseinkhojany** [ImaginativeShohag/Why-Not-Image-Carousel#79]

**Comment by ImaginativeShohag** [comment]
You must use a fixed height. You can use constraint layout and use `layout_constraintDimensionRatio` to maintain an aspect ratio if you don't want a fixed height.

**Comment by ImaginativeShohag** [comment]
You must use a fixed height. You can use constraint layout and use `layout_constraintDimensionRatio` to maintain an aspect ratio if you don't want a fixed height.
