### ISSUE TITLE
CarouselType.SHOWCASE not working

### ISSUE THREAD

**Issue by dharmendra79** [ImaginativeShohag/Why-Not-Image-Carousel#87]
CarouselType.SHOWCASE not working

**Comment by ImaginativeShohag** [comment]
To use `CarouselType.SHOWCASE` you need a custom fixed width layout. Please check out examples 3 and 4 from the [sample](https://github.com/ImaginativeShohag/Why-Not-Image-Carousel/blob/2e238b42061ea70aaff86dcd0092275f9fc5bf19/sample/src/main/java/org/imaginativeworld/whynotimagecarousel/sample/KotlinActivity.kt#L196).
