### ISSUE TITLE
How to ensure the Showcase Carousel is only able to scroll through one item at a time?

### ISSUE THREAD

**Issue by shwetankshrey** [ImaginativeShohag/Why-Not-Image-Carousel#88]
I have a Carousel with app:carouselType set to "SHOWCASE" and app:carouselGravity set to "CENTER". Currently on swiping through the carousel long enough, it scrolls through multiple CarouselItems. How do I ensure that the user can only scroll through the carousel one CarouselItem at a time?

**Comment by prometteursol** [comment]
Same issue here please can you tell as soon as possible. I also waiting for answer.

**Comment by ImaginativeShohag** [comment]
> How do I ensure that the user can only scroll through the carousel one CarouselItem at a time?

There is no ready to use way to do that.

You can fork the repo and update `CarouselLinearLayoutManager` class and slow down the scroll speed like [this](https://stackoverflow.com/a/36784136/2263329).

**Comment by prometteursol** [comment]
But for this you can use SnapHelper for recyclerview

**Comment by ImaginativeShohag** [comment]
@prometteursol You can try and if you succeed share the solution, please :). Thank you. I also will try if I get time.

**Comment by prometteursol** [comment]
I don't have access of Recyclerview of the library

**Comment by ImaginativeShohag** [comment]
I mean clone or fork the repo.

**Comment by prometteursol** [comment]
Okk
