### ISSUE TITLE
please allow moving the indicators to top of the screen, also the images take time to load how can i speed it up?

### ISSUE THREAD

**Issue by netef** [ImaginativeShohag/Why-Not-Image-Carousel#9]
title says it all :)
great library overall!!!

**Comment by ImaginativeShohag** [comment]
> please allow moving the indicators to top of the screen

Noted.

Meantime, you can add custom navigation buttons in your view and use `carousel.next()` and `carousel.previous()` function to navigate the carousel. Check out the [samples](https://github.com/ImaginativeShohag/Why-Not-Image-Carousel/tree/master/sample) for details.

> the images take time to load how can i speed it up

I used `Glide` library for image loading. The image loading speed depends on image size and internet speed. So you can try scaling down the image size to speed up the loading.

Any suggestion about speed up is welcome.
