### ISSUE TITLE
Could you help me to be able to do the CarouselType.SHOWCASE function that doesn't work, I really need it

### ISSUE THREAD

**Issue by katherineCruzG** [ImaginativeShohag/Why-Not-Image-Carousel#93]
I put it in the two ways that are in the repository and neither works, any solution for this error?

**Comment by ImaginativeShohag** [comment]
Please share some codes. Like the XMLs and init codes.

**Comment by katherineCruzG** [comment]
this is the code in xml
<org.imaginativeworld.whynotimagecarousel.ImageCarousel
        android:id="@+id/carousel"
        android:layout_width="match_parent"
        android:layout_height="300dp"
        app:imageScaleType="centerInside"
        app:carouselType="SHOWCASE"
        app:carouselGravity="CENTER"
        app:scaleOnScroll="true"
        app:carouselBackground="#ffff4444"

        />

This is the code in java
list.add(
                new CarouselItem(
                        R.drawable.fondo_3,
                        "Photo by Kimiya Oveisi on Unsplash"
                )
        );

        carousel.setCarouselType(CarouselType.SHOWCASE);

        carousel.addData(list);

**Comment by ImaginativeShohag** [comment]
Please check out the samples from [here](https://github.com/ImaginativeShohag/Why-Not-Image-Carousel/tree/master/sample).

To use the showcase, you need a custom layout for the items with fixed widths. Checkout the example 3 from [here](https://github.com/ImaginativeShohag/Why-Not-Image-Carousel/blob/2e238b42061ea70aaff86dcd0092275f9fc5bf19/sample/src/main/java/org/imaginativeworld/whynotimagecarousel/sample/KotlinActivity.kt#L196).

**Comment by katherineCruzG** [comment]
And that would add everything in the mainActivity? Type the code of example 3?
Or do I have to create one similar to that or could I use that?

**Comment by ImaginativeShohag** [comment]
Carousel properties can be set in the XML or in code. No issue.

But you have to create a custom layout for the carousel item. **Must have fixed width.**

**Comment by katherineCruzG** [comment]
and could you create that custom design in the xml or could you give me an example?

**Comment by matthewlu341** [comment]
The example you provided is in Kotlin, can you provide an example of how we could do it in Java? Thanks.

**Comment by ImaginativeShohag** [comment]
@matthewlu341 Java example already exists. Please check [this](https://github.com/ImaginativeShohag/Why-Not-Image-Carousel/blob/2e238b42061ea70aaff86dcd0092275f9fc5bf19/sample/src/main/java/org/imaginativeworld/whynotimagecarousel/sample/SampleFragment.java).

**Comment by ImaginativeShohag** [comment]
@katherineCruzG You will find the samples [here](https://github.com/ImaginativeShohag/Why-Not-Image-Carousel/tree/master/sample).
