### ISSUE TITLE
carousel background with white or transparent color is not working

### ISSUE THREAD

**Issue by ahmadhassan5** [ImaginativeShohag/Why-Not-Image-Carousel#98]
I have tried with multiple ways including custom layout, from xml, using background etc but didn’t succeed yet. Still it has some shade in upper and lower part.

        binding.carousel.carouselBackground = ColorDrawable(Color.parseColor("#00000000"))

Can you please fix this?
Thanks

**Comment by ImaginativeShohag** [comment]
Use the following in XML:

```xml
 <org.imaginativeworld.whynotimagecarousel.ImageCarousel
    app:showTopShadow="false"
    app:showBottomShadow="false"
```

Or, you can change the values programmatically like this:

```kotlin
carousel.showTopShadow = false
carousel.showBottomShadow = false
```

**Comment by ahmadhassan5** [comment]
Thanks a lot, Man!
